### ISSUE TITLE
How to generate hash for topic from external program?

### ISSUE THREAD

**Issue by emin63** [magit/orgit-forge#6]
Thanks for orgit-forge, I really like it and use it more and more.

Can you describe how to generate the hash for an `orgit-topic` link using the owner/repo and issue number? I know how to get the hash for an owner/repo using something like `(slot-value (forge-get-repository t) 'id)` so I could just store that but I don't know how to generate the part of the hash based on the issue number or issue id.

One use case for this is using the `gh` CLI from github to generate a list of issues I am tracking with `orgit-topic` links.

Thanks for any pointers you can provide.

**Comment by tarsius** [comment]
These ids are meaningless to anything but Forge itself, and things build on it. (But see `orgit-topic-store` for how to get them.)

**Comment by emin63** [comment]
> These ids are meaningless to anything but Forge itself, and things build on it. (But see `orgit-topic-store` for how to get them.)

OK, thanks. FYI: I ended up going a different route and wrote an elisp function which produces an org-table with links to prioritized issues: https://github.com/emin63/magit-priority-example/blob/main/magit-priority-example.el#L253

Thanks again for all the awesome stuff in magit.

**Comment by tarsius** [comment]
You are welcome!

(What's up with those closing parents?!)

**Comment by emin63** [comment]
> (What's up with those closing parents?!)

My instructor in college told me that LISP stands for "lots of irritating and silly parenthesis". Just kidding. It's just been a while since I've done lisp. I'll clean up the formatting soon when I fix some other things.

Any other feedback you have is welcome and appreciated. Thanks.

**Comment by tarsius** [comment]
Spring is here and my backlog is still long. So I won't have a closer look, but generally it looks sane.
