### ISSUE TITLE
Import of "ol" (from org) missing? 

### ISSUE THREAD

**Issue by moritzschaefer** [magit/orgit-forge#7]
When starting emacs, I get an error in orgit-forge (made apparent through debug mode):

```
Debugger entered--Lisp error: (void-function org-link-set-parameters)
* (org-link-set-parameters "orgit-topic" :store #'orgit-topic-store :follow #'orgit-topic-open :export #'orgit-topic-export :complete #'orgit-topic-complete-link)
  (closure (t) nil (org-link-set-parameters "orgit-topic" :store #'orgit-topic-store :follow #'orgit-topic-open :export #'orgit-topic-export :complete #'orgit-topic-complete-link))()
  funcall((closure (t) nil (org-link-set-parameters "orgit-topic" :store #'orgit-topic-store :follow #'orgit-topic-open :export #'orgit-topic-export :complete #'orgit-topic-complete-link)))
```

org-link-set-parameters is defined in ol.el (in org), so requiring `ol` might be necessary to fix this?

magit version: Magit 20220916.1716 [>= 3.3.0-git], Git 2.33.3, Emacs 28.1, gnu/linux

**Comment by tarsius** [comment]
`orgit-force` requires `orgit, which requires `org`, which require `ol`. That's with a development version of Org-Mode. What version are you using? Does its `org` not require `ol`?

**Comment by moritzschaefer** [comment]
Thank you for the swift response.

I think indeed the issue is on my end.
package-list-packages shows

  org                            9.5.5          available    gnu      Outline-based notes management and organizer

however org-version return 9.5.2 indicating that the emacs-delivered version of org-mode is used and not the installed org-mode package.
